### ISSUE TITLE
 Metrics do not enter on my server

### ISSUE THREAD

**Issue by 96luisescamilla** [kingkupps/SplunkARWeatherDemoToolkit#14]
Hello, I already have all the settings on the server, when the Start Polling is done the data is not shown on the server, there are only records like this example: 
![SharedScreenshot](https://user-images.githubusercontent.com/28199388/74198187-70040000-4c26-11ea-8646-85ee9882c4e0.jpg)

Is there any solution?

**Comment by kingkupps** [comment]
Hi @96luisescamilla, I have a few questions to help me debug this further:

1. Do any errors appear in the text box to the left after you begin polling?
2. Can you also confirm the index you're using is a metrics index as opposed to an events index?
3. When you click the "See All Uploaded Metrics", does the page correctly redirect to your Splunk instance? If so, is there any metric data there?
4. Can you post the search query you used to find the result you posted?

Thanks for using this! Feel free to reach out to me by email at jkuppel@splunk.com if you want to talk more about using Splunk Augmented Reality within your company.

**Comment by 96luisescamilla** [comment]
Hello thank you very much for answering...

1. Do any errors appear in the text box to the left after you begin polling?

![weather](https://user-images.githubusercontent.com/28199388/74370147-38b75f80-4d9c-11ea-91e3-1d1c98b81260.png)

**There is no error at the time of polling**

2. Can you also confirm the index you're using is a metrics index as opposed to an events index?

**It is an index of metrics**

3. When you click the "See All Uploaded Metrics", does the page correctly redirect to your Splunk instance? If so, is there any metric data there?

**When I click on "View all loaded metrics", the page is redirected correctly to my Splunk instance, but there is no metric data there**

4. Can you post the search query you used to find the result you posted?

| mstats avg(_value) as Average WHERE index="ar-weather-demo" AND metric_name=*



**_How should the data be viewed after polling in splunk?_**

**Comment by kingkupps** [comment]
Hmm this is strange, can you also post what the query is when you click on "See All Uploaded Metrics"?

It might also help to know more about your Splunk setup like:
1. Which Splunk version are you using?
2. Is your instance in a distributed search environment?

**Comment by 96luisescamilla** [comment]
My version of splunk Enterprise is 7.2.4.2

The query is:

| mstats avg(_value) as Average, count(_value) Count, latest(_value) as
Latest WHERE index="ar-weather-demo" AND metric_name=* BY metric_name
| eval Metric=metric_name
| table Metric, Count, Average, Latest

[image: Captura de pantalla (178).png]
*I attach screenshots of all settings*
----
Index:
[image: Captura de pantalla (177).png]
----
HEC:
[image: Captura de pantalla (176).png]
----
Weather Event Emitter:
[image: Captura de pantalla (175).png]
----
Global Settings HEC:
[image: Captura de pantalla (180).png]

**Comment by ryanwoconnor** [comment]
Hi @96luisescamilla,

I'm following this thread as well. I unfortunately can't see the most recent images you posted. Can you try once more to add them here?

Thank you,
Ryan

**Comment by 96luisescamilla** [comment]
I'm sorry, I try again.

My version of splunk Enterprise is 7.2.4.2

The query is:

| mstats avg(_value) as Average, count(_value) Count, latest(_value) as
Latest WHERE index="ar-weather-demo" AND metric_name=* BY metric_name
| eval Metric=metric_name
| table Metric, Count, Average, Latest

![Query](https://user-images.githubusercontent.com/28199388/74547913-7d650700-4f12-11ea-967c-89b9a92d7187.png)

*I attach screenshots of all settings*
----
Index:
![Index](https://user-images.githubusercontent.com/28199388/74547956-8d7ce680-4f12-11ea-92a4-876554489033.png)

----
HEC:
![HEC](https://user-images.githubusercontent.com/28199388/74547991-9b326c00-4f12-11ea-9326-5aa340addbb5.png)

----
Weather Event Emitter:
![WDE](https://user-images.githubusercontent.com/28199388/74548026-b1402c80-4f12-11ea-9b20-cad2fa6df130.png)

----
Global Settings HEC:
![GlobalSettings](https://user-images.githubusercontent.com/28199388/74548048-bac99480-4f12-11ea-84a6-6b2f06e3654e.png)

**Comment by ryanwoconnor** [comment]
Hi @96luisescamilla 

Can you do me a favor and change the default sourcetype for that token to something other than _json? That is a pre-trained sourcetype for JSON data and I believe this is the root cause of the issue. I was able to re-create the issue you had in a test environment and changing this resolved it. See the example below:

<img width="1680" alt="Screen Shot 2020-02-14 at 4 55 10 PM" src="https://user-images.githubusercontent.com/11879871/74570866-0b5ce400-4f4b-11ea-93e0-8c3a2c89af13.png">

Thank you,
Ryan

**Comment by 96luisescamilla** [comment]
Thanks you Ryan, effectively changing the sourcetype was correct, now I have the data in splunk! (y)

**Comment by 96luisescamilla** [comment]
Thanks you Ryan, effectively changing the sourcetype was correct, now I have the data in splunk!

**Comment by kingkupps** [comment]
Glad to hear the issue is resolved! Thanks again @ryanwoconnor

**Comment by sammylee8311** [comment]
@96luisescamilla Hi Luis, I'm the product Manager on Splunk AR. If you're interested, we can set up a call, and I can help you build out your use case. In addition, I can share what's upcoming on the roadmap. My email is sammyl@splunk.com. You can message me there.
